joint_limits:
  mecanum_joints:
    has_position_limits: false
    has_velocity_limits: false
    max_velocity: 0.8
    has_acceleration_limits: false
    max_acceleration: 10.0
    has_jerk_limits: false
    max_jerk: 100.0
